<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class LecturerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('lecturers')->insert([
            [
                'id' => 1,
                'code' => 'DSN001',
                'name' => 'Dr. Ahmad Fauzi',

                'nidn' => '10102122',
                'password' => Hash::make('password123'),

                'short_name' => 'AFZ',
                'place_of_birth' => 'Medan',
                'date_of_birth' => '1980-05-12',
                'address' => 'Jl. Setia Budi, Medan',
                'handphone' => '081234567890',
                'phone' => '061123456',
                'email' => 'ahmad.fauzi@kampus.ac.id',
                'front_title' => 'Dr.',
                'rear_title' => 'M.Kom',
                'first_degree_title' => 'S.Kom',
                'first_degree_major' => 'Teknik Informatika',
                'first_degree_university' => 'Universitas Sumatera Utara',
                'second_degree_title' => 'M.Kom',
                'second_degree_major' => 'Ilmu Komputer',
                'second_degree_university' => 'Universitas Indonesia',
                'religion' => 'islam',
                'sex' => 'Laki - Laki',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'code' => 'DSN002',
                'name' => 'Dr. Siti Rahmawati',

                'nidn' => '10203123',
                'password' => Hash::make('password123'),

                'short_name' => 'SRW',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '1982-08-22',
                'address' => 'Jl. Merdeka No. 10, Jakarta',
                'handphone' => '081234567891',
                'phone' => '021123457',
                'email' => 'siti.rahmawati@kampus.ac.id',
                'front_title' => 'Dr.',
                'rear_title' => 'M.T',
                'first_degree_title' => 'S.T',
                'first_degree_major' => 'Teknik Informatika',
                'first_degree_university' => 'Universitas Indonesia',
                'second_degree_title' => 'M.T',
                'second_degree_major' => 'Ilmu Komputer',
                'second_degree_university' => 'Institut Teknologi Bandung',
                'religion' => 'islam',
                'sex' => 'Perempuan',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'code' => 'DSN003',
                'name' => 'Budi Santoso',

                'nidn' => '10304124',
                'password' => Hash::make('password123'),

                'short_name' => 'BDS',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '1985-03-15',
                'address' => 'Jl. Raya Darmo, Surabaya',
                'handphone' => '081234567892',
                'phone' => '031123458',
                'email' => 'budi.santoso@kampus.ac.id',
                'front_title' => null,
                'rear_title' => 'S.Kom, M.Kom',
                'first_degree_title' => 'S.Kom',
                'first_degree_major' => 'Teknik Informatika',
                'first_degree_university' => 'Institut Teknologi Sepuluh Nopember',
                'second_degree_title' => 'M.Kom',
                'second_degree_major' => 'Ilmu Komputer',
                'second_degree_university' => 'Universitas Gadjah Mada',
                'religion' => 'islam',
                'sex' => 'Laki - Laki',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'code' => 'DSN004',
                'name' => 'Dewi Lestari',

                'nidn' => '10405125',
                'password' => Hash::make('password123'),

                'short_name' => 'DWL',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '1987-11-30',
                'address' => 'Jl. Setiabudi No. 20, Bandung',
                'handphone' => '081234567893',
                'phone' => '022123459',
                'email' => 'dewi.lestari@kampus.ac.id',
                'front_title' => null,
                'rear_title' => 'S.T, M.T',
                'first_degree_title' => 'S.T',
                'first_degree_major' => 'Teknik Informatika',
                'first_degree_university' => 'Institut Teknologi Bandung',
                'second_degree_title' => 'M.T',
                'second_degree_major' => 'Computer Science',
                'second_degree_university' => 'Universitas Gadjah Mada',
                'religion' => 'islam',
                'sex' => 'Perempuan',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'code' => 'DSN005',
                'name' => 'Rudi Hermawan',

                'nidn' => '10506126',
                'password' => Hash::make('password123'),

                'short_name' => 'RDH',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '1983-07-08',
                'address' => 'Jl. Kaliurang KM 5, Yogyakarta',
                'handphone' => '081234567894',
                'phone' => '027123460',
                'email' => 'rudi.hermawan@kampus.ac.id',
                'front_title' => null,
                'rear_title' => 'S.Kom, M.Eng',
                'first_degree_title' => 'S.Kom',
                'first_degree_major' => 'Ilmu Komputer',
                'first_degree_university' => 'Universitas Gadjah Mada',
                'second_degree_title' => 'M.Eng',
                'second_degree_major' => 'Computer Engineering',
                'second_degree_university' => 'Institut Teknologi Bandung',
                'religion' => 'islam',
                'sex' => 'Laki - Laki',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'code' => 'DSN006',
                'name' => 'Rina Marlina',

                'nidn' => '10607127',
                'password' => Hash::make('password123'),

                'short_name' => 'RML',
                'place_of_birth' => 'Padang',
                'date_of_birth' => '1990-01-20',
                'address' => 'Jl. Khatib Sulaiman, Padang',
                'handphone' => '081234567895',
                'phone' => '075123461',
                'email' => 'rina.marlina@kampus.ac.id',
                'front_title' => null,
                'rear_title' => 'S.Si, M.Si',
                'first_degree_title' => 'S.Si',
                'first_degree_major' => 'Matematika',
                'first_degree_university' => 'Universitas Andalas',
                'second_degree_title' => 'M.Si',
                'second_degree_major' => 'Ilmu Komputer',
                'second_degree_university' => 'Universitas Indonesia',
                'religion' => 'islam',
                'sex' => 'Perempuan',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'code' => 'DSN007',
                'name' => 'Agus Wijaya',

                'nidn' => '10708128',
                'password' => Hash::make('password123'),

                'short_name' => 'AGW',
                'place_of_birth' => 'Semarang',
                'date_of_birth' => '1986-09-14',
                'address' => 'Jl. Pahlawan No. 5, Semarang',
                'handphone' => '081234567896',
                'phone' => '024123462',
                'email' => 'agus.wijaya@kampus.ac.id',
                'front_title' => null,
                'rear_title' => 'S.Kom, M.Kom',
                'first_degree_title' => 'S.Kom',
                'first_degree_major' => 'Sistem Informasi',
                'first_degree_university' => 'Universitas Diponegoro',
                'second_degree_title' => 'M.Kom',
                'second_degree_major' => 'Teknik Informatika',
                'second_degree_university' => 'Universitas Indonesia',
                'religion' => 'islam',
                'sex' => 'Laki - Laki',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'code' => 'DSN008',
                'name' => 'Lina Handayani',

                'nidn' => '10809129',
                'password' => Hash::make('password123'),

                'short_name' => 'LNH',
                'place_of_birth' => 'Makassar',
                'date_of_birth' => '1988-12-05',
                'address' => 'Jl. Sultan Hasanuddin, Makassar',
                'handphone' => '081234567897',
                'phone' => '041123463',
                'email' => 'lina.handayani@kampus.ac.id',
                'front_title' => null,
                'rear_title' => 'S.T, M.T',
                'first_degree_title' => 'S.T',
                'first_degree_major' => 'Teknik Komputer',
                'first_degree_university' => 'Universitas Hasanuddin',
                'second_degree_title' => 'M.T',
                'second_degree_major' => 'Jaringan Komputer',
                'second_degree_university' => 'Institut Teknologi Bandung',
                'religion' => 'islam',
                'sex' => 'Perempuan',
                'status' => 'aktif',
                'visible_id' => 1,
                'program_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
